export const USER_STATE_CHANGE = 'USER_STATE_CHANGE'
export const USER_POSTS_STATE_CHANGE = 'USER_POSTS_STATE_CHANGE'
export const USER_FOLLOWING_STATE_CHANGE = 'USER_FOLLOWING_STATE_CHANGE'

export const FRIENDS_POSTS_STATE_CHANGE = 'FRIENDS_POSTS_STATE_CHANGE'
export const FRIENDS_LIKES_STATE_CHANGE = 'FRIENDS_LIKES_STATE_CHANGE'
export const FRIENDS_DATA_STATE_CHANGE = 'FRIENDS_DATA_STATE_CHANGE'

export const CLEAR_DATA = 'CLEAR_DATA'
